### ISSUE TITLE
Issue accessing public ipv w/out Route53 setup

### ISSUE THREAD

**Issue by jonathanlandGit** [bspeagle/Jenkins#1]
Great Jenkins setup. Im trying to run this on my own VPC and infra and have found that this is blocked via firewall. Do you know how to bypass that? Tried to modify the security groups inbound, etc., but have not found a workaround.

**Comment by bspeagle** [comment]
Hey Jonathan.

Wanted to make sure I understood the question - you want to access the Jenkins instance from the IP rather than a Route53 record?

**Comment by jonathanlandGit** [comment]
Thanks for the response. Yes, that is correct.

**Comment by bspeagle** [comment]
Oh ok. You can use the load balancer DNS instead of a route 53 record. The instances are in an ASG so there isn't a constant IP to expose which is why you use the load balancer dns.

Let me know if you have any questions.

**Comment by jonathanlandGit** [comment]
Perfect. Thanks, man.
